  [build]
    command = "npm run build"
    publish = "build/"
    functions = "functions/"

  [build.environment]
    NODE_VERSION = "14.17.0"

  [[headers]]
    for = "/*"
    [headers.values]
       X-Robots-Tag = "noindex"
